name: CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: wordcountservice
  IMAGE_TAG: latest
  REGION: europe-west1
  SERVICE: wordcountservice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - &setupjava
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - &cachemaven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn clean install -B -DskipTests=true
      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: |
            target/
            Dockerfile
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - *setupjava
      - *cachemaven
      - uses: actions/download-artifact@v4
        with:
          name: built-artifacts
      - run: mvn verify -B
      - uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/*.xml
      - uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: target/failsafe-reports/*.xml
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-artifacts
      - &gcpauth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud config set project ${GCP_PROJECT_ID}

      - run: |
          gcloud auth configure-docker --quiet
          docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG} .
          docker push gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG}

      - run: |
          gcloud run deploy ${SERVICE} \
            --image=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG} \
            --platform=managed \
            --region=${REGION} \
            --allow-unauthenticated \
            --no-traffic \
            --tag=staging

  e2e-tests:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - *gcpauth
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: export BASE_URL=$(gcloud run services describe ${SERVICE} --region ${REGION} --format "value(status.traffic.url)")
      - run: |
          cd e2e
          npm install
          npx playwright test
