name: Deploy to Staging
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: wordcountservice
  IMAGE_TAG: latest
  REGION: europe-west1
  SERVICE: wordcountservice

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-artifacts
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud config set project ${GCP_PROJECT_ID}

      - run: |
          gcloud auth configure-docker --quiet
          docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG} .
          docker push gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG}

      - run: |
          gcloud run deploy ${SERVICE} \
            --image=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG} \
            --platform=managed \
            --region=${REGION} \
            --allow-unauthenticated \
            --no-traffic \
            --tag=staging
